import { styles } from '../styles';
import type { PosterConfig } from '@/types/poster';
import { DEFAULT_CONFIG } from './defaults';

export interface PosterExample {
  id: string;
  name: string;
  description: string;
  config: PosterConfig;
}

const getStyle = (id: string) => styles.find(s => s.id === id) || styles[0];

export const POSTER_EXAMPLES: PosterExample[] = [
  {
    id: 'scottish-highlands',
    name: 'Scottish Highlands',
    description: 'Vintage nautical style showing the rugged coastline and lochs.',
    config: {
      ...DEFAULT_CONFIG,
      location: {
        name: 'Scottish Highlands',
        city: 'The Highlands',
        subtitle: 'Scotland',
        center: [-5.2, 57.1] as [number, number],
        bounds: [[-6.5, 56.2], [-4.0, 58.0]] as [[number, number], [number, number]],
        zoom: 7.4,
      },
      style: getStyle('vintage'),
      palette: getStyle('vintage').palettes.find(p => p.id === 'vintage-parchment') || getStyle('vintage').defaultPalette,
      typography: {
        ...DEFAULT_CONFIG.typography,
        titleFont: 'Playfair Display',
        titleSize: 5.5,
        titleWeight: 700,
        titleLetterSpacing: 0.12,
        titleAllCaps: true,
        subtitleSize: 5.1,
        showTitle: false,
        backdropHeight: 62,
        backdropAlpha: 0.9,
      },
      format: {
        ...DEFAULT_CONFIG.format,
        aspectRatio: '2:3',
        margin: 8,
        borderStyle: 'double',
        texture: 'paper',
        textureIntensity: 18,
      },
      layers: {
        ...DEFAULT_CONFIG.layers,
        streets: true,
        water: true,
        terrain: true,
        hillshadeExaggeration: 0.8,
        contours: true,
        contourDensity: 50,
        marker: false,
        'labels-admin': true,
        'labels-cities': true,
      }
    }
  },
  {
    id: 'hong-kong-midnight',
    name: 'Hong Kong',
    description: 'Dramatic "Midnight" view of the city between mountains and harbor.',
    config: {
      ...DEFAULT_CONFIG,
      location: {
        name: 'Hong Kong',
        city: 'Hong Kong',
        subtitle: 'China',
        center: [114.1694, 22.3193] as [number, number],
        bounds: [[113.82, 22.15], [114.45, 22.55]] as [[number, number], [number, number]],
        zoom: 10,
      },
      style: getStyle('midnight'),
      palette: getStyle('midnight').palettes.find(p => p.id === 'midnight-classic') || getStyle('midnight').defaultPalette,
      typography: {
        ...DEFAULT_CONFIG.typography,
        titleFont: 'Outfit',
        titleSize: 5.5,
        titleWeight: 700,
        titleLetterSpacing: 0.12,
        titleAllCaps: true,
        subtitleFont: 'Outfit',
        subtitleSize: 5.1,
        showTitle: false,
        showSubtitle: true,
        showCoordinates: true,
        position: 'bottom',
        textBackdrop: 'gradient',
        backdropHeight: 62,
        backdropAlpha: 0.9,
        maxWidth: 80,
      },
      format: {
        ...DEFAULT_CONFIG.format,
        aspectRatio: '2:3',
        orientation: 'portrait',
        margin: 8,
        borderStyle: 'double',
        texture: 'paper',
        textureIntensity: 18,
      },
      layers: {
        ...DEFAULT_CONFIG.layers,
        streets: true,
        buildings: false,
        water: true,
        parks: true,
        terrain: true,
        hillshadeExaggeration: 1.0,
        contours: false,
        contourDensity: 10,
        population: false,
        labels: true,
        labelSize: 0.8,
        labelMaxWidth: 10,
        marker: false,
        markerType: 'crosshair',
        roadWeight: 0.1,
        'labels-admin': true,
        'labels-cities': true,
      }
    }
  },
  {
    id: 'berlin-minimal',
    name: 'Berlin',
    description: 'A clean "Minimal" look at the German capital.',
    config: {
      ...DEFAULT_CONFIG,
      location: {
        name: 'Berlin',
        city: 'Berlin',
        subtitle: 'Germany',
        center: [13.405, 52.52] as [number, number],
        bounds: [[13.1, 52.35], [13.7, 52.68]] as [[number, number], [number, number]],
        zoom: 10,
      },
      style: getStyle('minimal'),
      palette: getStyle('minimal').palettes.find(p => p.id === 'minimal-navy') || getStyle('minimal').defaultPalette,
      typography: {
        ...DEFAULT_CONFIG.typography,
        titleFont: 'Inter',
        titleSize: 4.3,
        titleWeight: 700,
        titleLetterSpacing: 0.12,
        titleAllCaps: true,
        subtitleFont: 'Inter',
        subtitleSize: 4.7,
        showTitle: false,
        showSubtitle: true,
        showCoordinates: true,
        position: 'bottom',
        textBackdrop: 'gradient',
        backdropHeight: 28,
        backdropAlpha: 0.9,
        backdropSharpness: 97,
        maxWidth: 80,
      },
      format: {
        ...DEFAULT_CONFIG.format,
        aspectRatio: '1:1',
        orientation: 'portrait',
        margin: 8,
        borderStyle: 'double',
        texture: 'paper',
        textureIntensity: 18,
      },
      layers: {
        ...DEFAULT_CONFIG.layers,
        streets: true,
        buildings: false,
        water: true,
        parks: false,
        terrain: true,
        hillshadeExaggeration: 1,
        contours: false,
        contourDensity: 10,
        population: false,
        labels: true,
        labelSize: 0.8,
        labelMaxWidth: 10,
        marker: false,
        markerType: 'crosshair',
        roadWeight: 0.2,
        'labels-admin': true,
        'labels-cities': true,
      }
    }
  },
  {
    id: 'chicago-noir',
    name: 'Chicago Noir',
    description: 'A striking "Dark Mode" view of Chicago with silver highlights.',
    config: {
      ...DEFAULT_CONFIG,
      location: {
        name: 'Chicago',
        city: 'Chicago, IL',
        subtitle: 'Illinois, USA',
        center: [-87.6298, 41.8781] as [number, number],
        bounds: [[-87.85, 41.72], [-87.45, 42.05]] as [[number, number], [number, number]],
        zoom: 12,
      },
      style: getStyle('dark-mode'),
      palette: getStyle('dark-mode').palettes.find(p => p.id === 'dark-silver') || getStyle('dark-mode').defaultPalette,
      typography: {
        ...DEFAULT_CONFIG.typography,
        titleFont: 'Montserrat',
        titleSize: 5,
        titleWeight: 800,
        titleLetterSpacing: 0.08,
        titleAllCaps: true,
        subtitleFont: 'Montserrat',
        subtitleSize: 2.5,
        showTitle: true,
        showSubtitle: true,
        showCoordinates: true,
        position: 'bottom',
        textBackdrop: 'gradient',
        backdropHeight: 35,
        backdropAlpha: 1,
        backdropSharpness: 50,
        maxWidth: 80,
      },
      format: {
        ...DEFAULT_CONFIG.format,
        aspectRatio: '2:3',
        orientation: 'portrait',
        margin: 5,
        borderStyle: 'inset',
        texture: 'none',
        textureIntensity: 20,
      },
      layers: {
        ...DEFAULT_CONFIG.layers,
        streets: true,
        buildings: false,
        water: true,
        parks: true,
        terrain: true,
        hillshadeExaggeration: 0.6,
        contours: false,
        contourDensity: 50,
        population: false,
        labels: false,
        labelSize: 1,
        labelMaxWidth: 10,
        marker: true,
        markerType: 'crosshair',
        roadWeight: 0.4,
        'labels-admin': true,
        'labels-cities': true,
      }
    }
  },
  {
    id: 'tokyo-neon',
    name: 'Tokyo Neon',
    description: 'Vibrant neon glow over the Tokyo metropolis.',
    config: {
      ...DEFAULT_CONFIG,
      location: {
        name: 'Tokyo',
        city: 'Tokyo',
        subtitle: 'Japan',
        center: [139.75, 35.68] as [number, number],
        bounds: [[139.5, 35.5], [140.0, 35.9]] as [[number, number], [number, number]],
        zoom: 10,
      },
      style: getStyle('dark-mode'),
      palette: getStyle('dark-mode').palettes.find(p => p.id === 'dark-neon') || getStyle('dark-mode').defaultPalette,
      typography: {
        ...DEFAULT_CONFIG.typography,
        titleFont: 'Montserrat',
        titleSize: 4.3,
        titleWeight: 700,
        titleLetterSpacing: 0.12,
        titleAllCaps: true,
        subtitleFont: 'Montserrat',
        subtitleSize: 4.7,
        showTitle: false,
        showSubtitle: true,
        showCoordinates: true,
        position: 'bottom',
        textBackdrop: 'gradient',
        backdropHeight: 28,
        backdropAlpha: 0.9,
        backdropSharpness: 97,
        maxWidth: 80,
      },
      format: {
        ...DEFAULT_CONFIG.format,
        aspectRatio: '1:1',
        orientation: 'portrait',
        margin: 8,
        borderStyle: 'double',
        texture: 'paper',
        textureIntensity: 18,
      },
      layers: {
        ...DEFAULT_CONFIG.layers,
        streets: true,
        buildings: false,
        water: true,
        parks: false,
        terrain: true,
        hillshadeExaggeration: 1,
        contours: false,
        contourDensity: 10,
        population: false,
        labels: true,
        labelSize: 0.8,
        labelMaxWidth: 10,
        marker: false,
        markerType: 'crosshair',
        roadWeight: 0.2,
        'labels-admin': true,
        'labels-cities': true,
      }
    }
  },
  {
    id: 'caribbean-coral',
    name: 'The Caribbean',
    description: 'A vibrant "Organic" style view of the Caribbean islands with coral tones.',
    config: {
      ...DEFAULT_CONFIG,
      location: {
        name: '',
        city: 'The Caribbean',
        subtitle: '',
        center: [-68.5, 18.0] as [number, number],
        bounds: [[-75.0, 12.0], [-60.0, 24.0]] as [[number, number], [number, number]],
        zoom: 5,
      },
      style: getStyle('organic'),
      palette: getStyle('organic').palettes.find(p => p.id === 'organic-coral-reef') || getStyle('organic').defaultPalette,
      typography: {
        ...DEFAULT_CONFIG.typography,
        titleFont: 'Outfit',
        titleSize: 5,
        titleWeight: 800,
        titleLetterSpacing: 0.08,
        titleAllCaps: true,
        subtitleFont: 'Outfit',
        subtitleSize: 4.8,
        showTitle: false,
        showSubtitle: true,
        showCoordinates: false,
        position: 'bottom',
        textBackdrop: 'gradient',
        backdropHeight: 26,
        backdropAlpha: 1,
        backdropSharpness: 52,
        maxWidth: 80,
      },
      format: {
        ...DEFAULT_CONFIG.format,
        aspectRatio: '2:3',
        orientation: 'portrait',
        margin: 5,
        borderStyle: 'thick',
        texture: 'none',
        textureIntensity: 20,
      },
      layers: {
        ...DEFAULT_CONFIG.layers,
        streets: true,
        buildings: false,
        water: true,
        parks: true,
        terrain: true,
        terrainUnderWater: true,
        hillshadeExaggeration: 0.5,
        contours: false,
        contourDensity: 50,
        population: false,
        labels: false,
        labelSize: 1,
        labelMaxWidth: 10,
        labelStyle: 'elevated',
        marker: false,
        markerType: 'crosshair',
        roadWeight: 1,
        'labels-admin': true,
        'labels-cities': true,
      }
    }
  },
  {
    id: 'morocco-pueblo',
    name: 'Morocco',
    description: 'An "Organic" style view of Morocco with pueblo tones.',
    config: {
      ...DEFAULT_CONFIG,
      location: {
        name: 'Morocco',
        city: 'Morocco',
        subtitle: '',
        center: [-7.0, 31.5] as [number, number],
        bounds: [[-12.0, 27.5], [-1.0, 35.5]] as [[number, number], [number, number]],
        zoom: 5.5,
      },
      style: getStyle('organic'),
      palette: getStyle('organic').palettes.find(p => p.id === 'organic-pueblo') || getStyle('organic').defaultPalette,
      typography: {
        ...DEFAULT_CONFIG.typography,
        titleFont: 'Outfit',
        titleSize: 5.5,
        titleWeight: 700,
        titleLetterSpacing: 0.12,
        titleAllCaps: true,
        subtitleFont: 'Outfit',
        subtitleSize: 4.1,
        showTitle: false,
        showSubtitle: true,
        showCoordinates: false,
        position: 'bottom',
        textBackdrop: 'gradient',
        backdropHeight: 20,
        backdropAlpha: 0.9,
        backdropSharpness: 77,
        maxWidth: 80,
      },
      format: {
        ...DEFAULT_CONFIG.format,
        aspectRatio: '3:4',
        orientation: 'portrait',
        margin: 8,
        borderStyle: 'thick',
        texture: 'paper',
        textureIntensity: 9,
      },
      layers: {
        ...DEFAULT_CONFIG.layers,
        streets: false,
        buildings: false,
        water: true,
        parks: false,
        terrain: true,
        hillshadeExaggeration: 1,
        contours: false,
        contourDensity: 10,
        population: false,
        labels: true,
        labelSize: 0.8,
        labelMaxWidth: 20,
        marker: true,
        markerType: 'crosshair',
        roadWeight: 1.7,
        'labels-admin': true,
        'labels-cities': true,
      }
    }
  },
  {
    id: 'new-zealand-botanical',
    name: 'New Zealand',
    description: 'A circular "Watercolor" view of New Zealand with botanical tones.',
    config: {
      ...DEFAULT_CONFIG,
      location: {
        name: '',
        city: 'New Zealand',
        subtitle: '',
        center: [172.5, -41.5] as [number, number],
        bounds: [[166.0, -47.5], [179.0, -34.0]] as [[number, number], [number, number]],
        zoom: 4.5,
      },
      style: getStyle('watercolor'),
      palette: getStyle('watercolor').palettes.find(p => p.id === 'watercolor-botanical') || getStyle('watercolor').defaultPalette,
      typography: {
        ...DEFAULT_CONFIG.typography,
        titleFont: 'Quicksand',
        titleSize: 5,
        titleWeight: 800,
        titleLetterSpacing: 0.08,
        titleAllCaps: true,
        subtitleFont: 'Quicksand',
        subtitleSize: 4.8,
        showTitle: false,
        showSubtitle: false,
        showCoordinates: false,
        position: 'bottom',
        textBackdrop: 'none',
        backdropHeight: 26,
        backdropAlpha: 1,
        backdropSharpness: 52,
        maxWidth: 80,
      },
      format: {
        ...DEFAULT_CONFIG.format,
        aspectRatio: '1:1',
        orientation: 'portrait',
        margin: 5,
        borderStyle: 'thick',
        maskShape: 'circular',
        texture: 'none',
        textureIntensity: 20,
      },
      layers: {
        ...DEFAULT_CONFIG.layers,
        streets: true,
        buildings: false,
        water: true,
        parks: true,
        terrain: true,
        terrainUnderWater: true,
        hillshadeExaggeration: 0.5,
        contours: false,
        contourDensity: 50,
        population: false,
        labels: false,
        labelSize: 1,
        labelMaxWidth: 10,
        labelStyle: 'elevated',
        marker: false,
        markerType: 'crosshair',
        roadWeight: 1,
        'labels-admin': true,
        'labels-cities': true,
      }
    }
  },
  {
    id: 'swiss-alps-topo',
    name: 'Swiss Alps',
    description: 'A topographic survey-style view of the Swiss Alps.',
    config: {
      ...DEFAULT_CONFIG,
      location: {
        name: 'Swiss Alps',
        city: 'The Alps',
        subtitle: 'Switzerland',
        center: [8.2275, 46.8182] as [number, number],
        bounds: [[6.5, 45.8], [10.5, 47.8]] as [[number, number], [number, number]],
        zoom: 8,
      },
      style: getStyle('topographic'),
      palette: getStyle('topographic').palettes.find(p => p.id === 'topo-survey') || getStyle('topographic').defaultPalette,
      typography: {
        ...DEFAULT_CONFIG.typography,
        titleFont: 'Spectral',
        titleSize: 5,
        titleWeight: 800,
        titleLetterSpacing: 0.08,
        titleAllCaps: true,
        subtitleFont: 'Spectral',
        subtitleSize: 5.5,
        showTitle: false,
        showSubtitle: true,
        showCoordinates: true,
        position: 'bottom',
        textBackdrop: 'gradient',
        backdropHeight: 35,
        backdropAlpha: 1,
        backdropSharpness: 50,
        maxWidth: 80,
      },
      format: {
        ...DEFAULT_CONFIG.format,
        aspectRatio: '2:3',
        orientation: 'portrait',
        margin: 5,
        borderStyle: 'inset',
        maskShape: 'rectangular',
        compassRose: false,
        texture: 'none',
        textureIntensity: 20,
      },
      layers: {
        ...DEFAULT_CONFIG.layers,
        streets: true,
        buildings: false,
        water: true,
        parks: true,
        terrain: true,
        terrainUnderWater: true,
        hillshadeExaggeration: 1,
        contours: false,
        contourDensity: 50,
        population: false,
        pois: true,
        labels: false,
        labelSize: 1,
        labelMaxWidth: 10,
        labelStyle: 'elevated',
        boundaries: false,
        marker: false,
        markerType: 'crosshair',
        roadWeight: 1,
        'labels-admin': false,
        'labels-cities': false,
      }
    }
  }
];
