import { styles } from '../styles';
import type { PosterConfig } from '@/types/poster';
import { DEFAULT_CONFIG } from './defaults';

export interface PosterExample {
  id: string;
  name: string;
  description: string;
  config: PosterConfig;
}

const getStyle = (id: string) => styles.find(s => s.id === id) || styles[0];

export const POSTER_EXAMPLES: PosterExample[] = [
  {
    id: 'chesapeake',
    name: 'Chesapeake Bay',
    description: 'Vintage nautical style showing the vast bay network.',
    config: {
      ...DEFAULT_CONFIG,
      location: {
        name: 'Chesapeake Bay',
        city: 'The Chesapeke',
        subtitle: 'United States',
        center: [-76.17419096218805, 37.8593958816429] as [number, number],
        bounds: [[-76.35, 36.75], [-75.75, 37.15]] as [[number, number], [number, number]],
        zoom: 7.381973990444137,
      },
      style: getStyle('vintage'),
      palette: getStyle('vintage').palettes.find(p => p.id === 'vintage-parchment') || getStyle('vintage').defaultPalette,
      typography: {
        ...DEFAULT_CONFIG.typography,
        titleFont: 'Playfair Display',
        titleSize: 5.5,
        titleWeight: 700,
        titleLetterSpacing: 0.12,
        titleAllCaps: true,
        subtitleSize: 5.1,
        showTitle: false,
        backdropHeight: 62,
        backdropAlpha: 0.9,
      },
      format: {
        ...DEFAULT_CONFIG.format,
        aspectRatio: '2:3',
        margin: 8,
        borderStyle: 'double',
        texture: 'paper',
        textureIntensity: 18,
      },
      layers: {
        ...DEFAULT_CONFIG.layers,
        streets: true,
        water: true,
        terrain: true,
        hillshadeExaggeration: 0.8,
        contours: true,
        contourDensity: 50,
        marker: false,
        'labels-admin': true,
        'labels-cities': true,
      }
    }
  },
  {
    id: 'salt-lake-city',
    name: 'Salt Lake City',
    description: 'Dramatic "Midnight" view of the city between the mountains and the lake.',
    config: {
      ...DEFAULT_CONFIG,
      location: {
        name: 'Salt Lake City',
        city: 'Salt Lake City, UT',
        subtitle: 'Utah, United States',
        center: [-111.886797, 40.7596198] as [number, number],
        bounds: [[-112.1013916, 40.6999263], [-111.7404843, 40.8533905]] as [[number, number], [number, number]],
        zoom: 10,
      },
      style: getStyle('midnight'),
      palette: getStyle('midnight').palettes.find(p => p.id === 'midnight-classic') || getStyle('midnight').defaultPalette,
      typography: {
        ...DEFAULT_CONFIG.typography,
        titleFont: 'Outfit',
        titleSize: 5.5,
        titleWeight: 700,
        titleLetterSpacing: 0.12,
        titleAllCaps: true,
        subtitleFont: 'Outfit',
        subtitleSize: 5.1,
        showTitle: false,
        showSubtitle: true,
        showCoordinates: true,
        position: 'bottom',
        textBackdrop: 'gradient',
        backdropHeight: 62,
        backdropAlpha: 0.9,
        maxWidth: 80,
      },
      format: {
        ...DEFAULT_CONFIG.format,
        aspectRatio: '2:3',
        orientation: 'portrait',
        margin: 8,
        borderStyle: 'double',
        texture: 'paper',
        textureIntensity: 18,
      },
      layers: {
        ...DEFAULT_CONFIG.layers,
        streets: true,
        buildings: false,
        water: true,
        parks: true,
        terrain: true,
        hillshadeExaggeration: 1.0,
        contours: false,
        contourDensity: 10,
        population: false,
        labels: true,
        labelSize: 0.8,
        labelMaxWidth: 10,
        marker: false,
        markerType: 'crosshair',
        roadWeight: 0.1,
        'labels-admin': true,
        'labels-cities': true,
      }
    }
  },
  {
    id: 'tucson-minimal',
    name: 'Tucson',
    description: 'A clean "Minimal" look at the Arizona desert city.',
    config: {
      ...DEFAULT_CONFIG,
      location: {
        name: 'Tucson',
        city: 'Tucson, AZ',
        subtitle: 'Arizona, United States',
        center: [-110.96359522925843, 32.158429280115655] as [number, number],
        bounds: [[-111.15, 32.05], [-110.75, 32.35]] as [[number, number], [number, number]],
        zoom: 9.799049962367631,
      },
      style: getStyle('minimal'),
      palette: getStyle('minimal').palettes.find(p => p.id === 'minimal-navy') || getStyle('minimal').defaultPalette,
      typography: {
        ...DEFAULT_CONFIG.typography,
        titleFont: 'Inter',
        titleSize: 4.3,
        titleWeight: 700,
        titleLetterSpacing: 0.12,
        titleAllCaps: true,
        subtitleFont: 'Inter',
        subtitleSize: 4.7,
        showTitle: false,
        showSubtitle: true,
        showCoordinates: true,
        position: 'bottom',
        textBackdrop: 'gradient',
        backdropHeight: 28,
        backdropAlpha: 0.9,
        backdropSharpness: 97,
        maxWidth: 80,
      },
      format: {
        ...DEFAULT_CONFIG.format,
        aspectRatio: '1:1',
        orientation: 'portrait',
        margin: 8,
        borderStyle: 'double',
        texture: 'paper',
        textureIntensity: 18,
      },
      layers: {
        ...DEFAULT_CONFIG.layers,
        streets: true,
        buildings: false,
        water: true,
        parks: false,
        terrain: true,
        hillshadeExaggeration: 1,
        contours: false,
        contourDensity: 10,
        population: false,
        labels: true,
        labelSize: 0.8,
        labelMaxWidth: 10,
        marker: false,
        markerType: 'crosshair',
        roadWeight: 0.2,
        'labels-admin': true,
        'labels-cities': true,
      }
    }
  },
  {
    id: 'san-francisco-dark',
    name: 'San Francisco Noir',
    description: 'A striking "Dark Mode" view of San Francisco with silver highlights.',
    config: {
      ...DEFAULT_CONFIG,
      location: {
        name: 'San Francisco',
        city: 'San Francisco, CA',
        subtitle: 'California, USA',
        center: [-122.4194, 37.7749] as [number, number],
        bounds: [[-122.5179, 37.7038], [-122.3774, 37.8324]] as [[number, number], [number, number]],
        zoom: 12,
      },
      style: getStyle('dark-mode'),
      palette: getStyle('dark-mode').palettes.find(p => p.id === 'dark-silver') || getStyle('dark-mode').defaultPalette,
      typography: {
        ...DEFAULT_CONFIG.typography,
        titleFont: 'Montserrat',
        titleSize: 5,
        titleWeight: 800,
        titleLetterSpacing: 0.08,
        titleAllCaps: true,
        subtitleFont: 'Montserrat',
        subtitleSize: 2.5,
        showTitle: true,
        showSubtitle: true,
        showCoordinates: true,
        position: 'bottom',
        textBackdrop: 'gradient',
        backdropHeight: 35,
        backdropAlpha: 1,
        backdropSharpness: 50,
        maxWidth: 80,
      },
      format: {
        ...DEFAULT_CONFIG.format,
        aspectRatio: '2:3',
        orientation: 'portrait',
        margin: 5,
        borderStyle: 'inset',
        texture: 'none',
        textureIntensity: 20,
      },
      layers: {
        ...DEFAULT_CONFIG.layers,
        streets: true,
        buildings: false,
        water: true,
        parks: true,
        terrain: true,
        hillshadeExaggeration: 0.6,
        contours: false,
        contourDensity: 50,
        population: false,
        labels: false,
        labelSize: 1,
        labelMaxWidth: 10,
        marker: true,
        markerType: 'crosshair',
        roadWeight: 0.4,
        'labels-admin': true,
        'labels-cities': true,
      }
    }
  },
  {
    id: 'the-channel-neon',
    name: 'The Channel Neon',
    description: 'Vibrant neon glow over the English Channel.',
    config: {
      ...DEFAULT_CONFIG,
      location: {
        name: 'The Channel',
        city: 'The Channel',
        subtitle: 'English Channel',
        center: [1.171034135519335, 50.52543799494359] as [number, number],
        bounds: [[-111.15, 32.05], [-110.75, 32.35]] as [[number, number], [number, number]],
        zoom: 5.805587920440557,
      },
      style: getStyle('dark-mode'),
      palette: getStyle('dark-mode').palettes.find(p => p.id === 'dark-neon') || getStyle('dark-mode').defaultPalette,
      typography: {
        ...DEFAULT_CONFIG.typography,
        titleFont: 'Montserrat',
        titleSize: 4.3,
        titleWeight: 700,
        titleLetterSpacing: 0.12,
        titleAllCaps: true,
        subtitleFont: 'Montserrat',
        subtitleSize: 4.7,
        showTitle: false,
        showSubtitle: true,
        showCoordinates: true,
        position: 'bottom',
        textBackdrop: 'gradient',
        backdropHeight: 28,
        backdropAlpha: 0.9,
        backdropSharpness: 97,
        maxWidth: 80,
      },
      format: {
        ...DEFAULT_CONFIG.format,
        aspectRatio: '1:1',
        orientation: 'portrait',
        margin: 8,
        borderStyle: 'double',
        texture: 'paper',
        textureIntensity: 18,
      },
      layers: {
        ...DEFAULT_CONFIG.layers,
        streets: true,
        buildings: false,
        water: true,
        parks: false,
        terrain: true,
        hillshadeExaggeration: 1,
        contours: false,
        contourDensity: 10,
        population: false,
        labels: true,
        labelSize: 0.8,
        labelMaxWidth: 10,
        marker: false,
        markerType: 'crosshair',
        roadWeight: 0.2,
        'labels-admin': true,
        'labels-cities': true,
      }
    }
  },
  {
    id: 'organic-north-america',
    name: 'Organic North America',
    description: 'A vibrant "Organic" style view of the North American continent with coral tones.',
    config: {
      ...DEFAULT_CONFIG,
      location: {
        name: '',
        city: 'North America',
        subtitle: '',
        center: [-92.02849409103771, 9.479108070782175] as [number, number],
        bounds: [[-77.1130377, 38.862957], [-77.1128569, 38.8630805]] as [[number, number], [number, number]],
        zoom: 1.2854311188678398,
      },
      style: getStyle('organic'),
      palette: getStyle('organic').palettes.find(p => p.id === 'organic-coral-reef') || getStyle('organic').defaultPalette,
      typography: {
        ...DEFAULT_CONFIG.typography,
        titleFont: 'Outfit',
        titleSize: 5,
        titleWeight: 800,
        titleLetterSpacing: 0.08,
        titleAllCaps: true,
        subtitleFont: 'Outfit',
        subtitleSize: 4.8,
        showTitle: false,
        showSubtitle: true,
        showCoordinates: false,
        position: 'bottom',
        textBackdrop: 'gradient',
        backdropHeight: 26,
        backdropAlpha: 1,
        backdropSharpness: 52,
        maxWidth: 80,
      },
      format: {
        ...DEFAULT_CONFIG.format,
        aspectRatio: '2:3',
        orientation: 'portrait',
        margin: 5,
        borderStyle: 'thick',
        texture: 'none',
        textureIntensity: 20,
      },
      layers: {
        ...DEFAULT_CONFIG.layers,
        streets: true,
        buildings: false,
        water: true,
        parks: true,
        terrain: true,
        terrainUnderWater: true,
        hillshadeExaggeration: 0.5,
        contours: false,
        contourDensity: 50,
        population: false,
        labels: false,
        labelSize: 1,
        labelMaxWidth: 10,
        labelStyle: 'elevated',
        marker: false,
        markerType: 'crosshair',
        roadWeight: 1,
        'labels-admin': true,
        'labels-cities': true,
      }
    }
  },
  {
    id: 'midatlantic-pueblo',
    name: 'The Midatlantic',
    description: 'An "Organic" style view of the Midatlantic region with pueblo tones.',
    config: {
      ...DEFAULT_CONFIG,
      location: {
        name: 'The Midatlantic',
        city: 'The Midatlantic',
        subtitle: '',
        center: [-76.20066635491213, 38.15458777720772] as [number, number],
        bounds: [[-77.0688043, 39.0140765], [-77.0687043, 39.0141765]] as [[number, number], [number, number]],
        zoom: 6.85796882629819,
      },
      style: getStyle('organic'),
      palette: getStyle('organic').palettes.find(p => p.id === 'organic-pueblo') || getStyle('organic').defaultPalette,
      typography: {
        ...DEFAULT_CONFIG.typography,
        titleFont: 'Outfit',
        titleSize: 5.5,
        titleWeight: 700,
        titleLetterSpacing: 0.12,
        titleAllCaps: true,
        subtitleFont: 'Outfit',
        subtitleSize: 4.1,
        showTitle: false,
        showSubtitle: true,
        showCoordinates: false,
        position: 'bottom',
        textBackdrop: 'gradient',
        backdropHeight: 20,
        backdropAlpha: 0.9,
        backdropSharpness: 77,
        maxWidth: 80,
      },
      format: {
        ...DEFAULT_CONFIG.format,
        aspectRatio: '3:4',
        orientation: 'portrait',
        margin: 8,
        borderStyle: 'thick',
        texture: 'paper',
        textureIntensity: 9,
      },
      layers: {
        ...DEFAULT_CONFIG.layers,
        streets: false,
        buildings: false,
        water: true,
        parks: false,
        terrain: true,
        hillshadeExaggeration: 1,
        contours: false,
        contourDensity: 10,
        population: false,
        labels: true,
        labelSize: 0.8,
        labelMaxWidth: 20,
        marker: true,
        markerType: 'crosshair',
        roadWeight: 1.7,
        'labels-admin': true,
        'labels-cities': true,
      }
    }
  },
  {
    id: 'north-america-botanical',
    name: 'North America Botanical',
    description: 'A circular "Watercolor" view of the North American continent with botanical tones.',
    config: {
      ...DEFAULT_CONFIG,
      location: {
        name: '',
        city: 'North America',
        subtitle: '',
        center: [-99.53825302507505, 53.34358203851335] as [number, number],
        bounds: [[-77.1130377, 38.862957], [-77.1128569, 38.8630805]] as [[number, number], [number, number]],
        zoom: 2.613024419786261,
      },
      style: getStyle('watercolor'),
      palette: getStyle('watercolor').palettes.find(p => p.id === 'watercolor-botanical') || getStyle('watercolor').defaultPalette,
      typography: {
        ...DEFAULT_CONFIG.typography,
        titleFont: 'Quicksand',
        titleSize: 5,
        titleWeight: 800,
        titleLetterSpacing: 0.08,
        titleAllCaps: true,
        subtitleFont: 'Quicksand',
        subtitleSize: 4.8,
        showTitle: false,
        showSubtitle: false,
        showCoordinates: false,
        position: 'bottom',
        textBackdrop: 'none',
        backdropHeight: 26,
        backdropAlpha: 1,
        backdropSharpness: 52,
        maxWidth: 80,
      },
      format: {
        ...DEFAULT_CONFIG.format,
        aspectRatio: '1:1',
        orientation: 'portrait',
        margin: 5,
        borderStyle: 'thick',
        maskShape: 'circular',
        texture: 'none',
        textureIntensity: 20,
      },
      layers: {
        ...DEFAULT_CONFIG.layers,
        streets: true,
        buildings: false,
        water: true,
        parks: true,
        terrain: true,
        terrainUnderWater: true,
        hillshadeExaggeration: 0.5,
        contours: false,
        contourDensity: 50,
        population: false,
        labels: false,
        labelSize: 1,
        labelMaxWidth: 10,
        labelStyle: 'elevated',
        marker: false,
        markerType: 'crosshair',
        roadWeight: 1,
        'labels-admin': true,
        'labels-cities': true,
      }
    }
  },
  {
    id: 'kennedy-space-center',
    name: 'Kennedy Space Center',
    description: 'A topographic survey-style view of LC-39B launch complex at Cape Canaveral.',
    config: {
      ...DEFAULT_CONFIG,
      location: {
        name: 'Kennedy Space Center',
        city: 'LC-39B',
        subtitle: 'Cape Canaveral, Florida, United States',
        center: [-80.620843347, 28.62686961091171] as [number, number],
        bounds: [[-80.5751454, 28.4377832], [-80.5686859, 28.4463163]] as [[number, number], [number, number]],
        zoom: 14,
      },
      style: getStyle('topographic'),
      palette: getStyle('topographic').palettes.find(p => p.id === 'topo-survey') || getStyle('topographic').defaultPalette,
      typography: {
        ...DEFAULT_CONFIG.typography,
        titleFont: 'Spectral',
        titleSize: 5,
        titleWeight: 800,
        titleLetterSpacing: 0.08,
        titleAllCaps: true,
        subtitleFont: 'Spectral',
        subtitleSize: 5.5,
        showTitle: false,
        showSubtitle: true,
        showCoordinates: true,
        position: 'bottom',
        textBackdrop: 'gradient',
        backdropHeight: 35,
        backdropAlpha: 1,
        backdropSharpness: 50,
        maxWidth: 80,
      },
      format: {
        ...DEFAULT_CONFIG.format,
        aspectRatio: '2:3',
        orientation: 'portrait',
        margin: 5,
        borderStyle: 'inset',
        maskShape: 'rectangular',
        compassRose: false,
        texture: 'none',
        textureIntensity: 20,
      },
      layers: {
        ...DEFAULT_CONFIG.layers,
        streets: true,
        buildings: false,
        water: true,
        parks: true,
        terrain: true,
        terrainUnderWater: true,
        hillshadeExaggeration: 1,
        contours: false,
        contourDensity: 50,
        population: false,
        pois: true,
        labels: false,
        labelSize: 1,
        labelMaxWidth: 10,
        labelStyle: 'elevated',
        boundaries: false,
        marker: false,
        markerType: 'crosshair',
        roadWeight: 1,
        'labels-admin': false,
        'labels-cities': false,
      }
    }
  }
];

